### ISSUE TITLE
NaN & undefinied bug in building values on beta branch.

### ISSUE THREAD

**Issue by Existence-dev** [Existence-dev/bloodorange-clicker#3]
When attempting to make the getcookies(); function capable of handling multiple cookies, I may have inadvertently broke the cookie system.

**Comment by Existence-dev** [comment]
Jesus christ is my error handling shitty. I think it's like my 15th commit today just trying to fix it

**Comment by Emonora** [comment]
Fixed it, however, it may still provide Nan undefined, or null values on error. You may want to check the dev console if it produces an error like that, and report the error that you recieve.
